django_interview/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models


class Poll(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="questions")
    question_text = models.CharField(max_length=200)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.template import RequestContext


from .models import Poll
from .models import Question


def index(request):
    polls = Poll.objects.prefetch_related('questions__choices').order_by('-pub_date')[:100]
    context = {'polls': polls}

    return render_to_response('polls/index.html', context,
                              context_instance=RequestContext(request))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css" />
    <title>My amazing blog</title>
</head>

<body>
    <div id="sidebar">
        <ul>
        </ul>
    </div>

    <div id="content">
      {% autoescape off %}
      <h1>{% block title %}{% endblock %}</h1>
      {% block content %}
      {% endblock %}
      {% endautoescape %}
    </div>
</body>
</html>

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}
{{ question }}
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}

{% if polls %}
<ul>
  {% for poll in polls %}
  <li>
    {{poll.name}}
    <ul>
    {% for question in poll.questions.all %}
      <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        <ul>
          {% for choice in question.choices.all %}
            <li>
              {{choice.choice_text}}
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
    </ul>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

{% endblock %}